### ISSUE TITLE
[BUG] NX test error

### ISSUE THREAD

**Issue by t-ricci-delta** [nx-dotnet/nx-dotnet#290]
**Describe the bug**
Launching `nx test` fails (I have both an angular frontend and .net backend)

**To Reproduce**

1. Genereate new NX workspace
2. Install and initialize nx-dotnet
3. Generate angular frontend application
4. Generate .NET backend application (webapi)
5. run command `nx test`
6. Observe it fails when trying to run .net tests

**Expected behavior**
Run both angular and .net tests

**Logs**
```
λ npm test

> social-event-dt@0.0.0 test
> nx test

? Would you like to share anonymous usage data about this project with the Angular Team at
Google under Google’s Privacy Policy at https://policies.google.com/privacy? For more
details and how to change this setting, see https://angular.io/analytics. No
No tests found, exiting with code 0
An unhandled exception occurred: Cannot find builder "@nx-dotnet/core:test".
See "C:\Users\TOMMAS~1.RIC\AppData\Local\Temp\ng-89olYy\angular-errors.log" for further details.


λ cat C:\Users\TOMMAS~1.RIC\AppData\Local\Temp\ng-89olYy\angular-errors.log
[error] Error: Cannot find builder "@nx-dotnet/core:test".
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (C:\Users\tommaso.ricci\source\repos\social-event-dt\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:125:19)
    at TestCommand.runSingleTarget (C:\Users\tommaso.ricci\source\repos\social-event-dt\node_modules\@angular\cli\models\architect-command.js:162:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TestCommand.runArchitectTarget (C:\Users\tommaso.ricci\source\repos\social-event-dt\node_modules\@angular\cli\models\architect-command.js:197:31)
    at async TestCommand.validateAndRun (C:\Users\tommaso.ricci\source\repos\social-event-dt\node_modules\@angular\cli\models\command.js:136:22)
    at async runCommand (C:\Users\tommaso.ricci\source\repos\social-event-dt\node_modules\@angular\cli\models\command-runner.js:224:24)
    at async default_1 (C:\Users\tommaso.ricci\source\repos\social-event-dt\node_modules\@angular\cli\lib\cli\index.js:85:31)
```

**Environment:**
```
λ nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.13.0
  OS   : win32 x64
  npm  : 8.1.4

  nx : 13.3.1
  @nrwl/angular : 13.3.1
  @nrwl/cli : 13.3.1
  @nrwl/cypress : 13.3.1
  @nrwl/devkit : 13.3.1
  @nrwl/eslint-plugin-nx : 13.3.1
  @nrwl/express : undefined
  @nrwl/jest : 13.3.1
  @nrwl/linter : 13.3.1
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.1
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.1
  @nrwl/storybook : 13.3.1
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.0
         @angular/common: 13.0.0
         @angular/compiler: 13.0.0
         @angular/core: 13.0.0
         @angular/forms: 13.0.0
         @angular/platform-browser: 13.0.0
         @angular/platform-browser-dynamic: 13.0.0
         @angular/router: 13.0.0
         @angular-devkit/build-angular: 13.0.4
         @angular/cli: 13.0.4
         @angular/compiler-cli: 13.0.0
         @angular/language-service: 13.0.0
         @nx-dotnet/core: 1.8.0

(node:21528) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\tommaso.ricci\source\repos\social-event-dt\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

```

Similar to #291

**Comment by t-ricci-delta** [comment]
> @t-ricci-delta This issue, as well as the similar issue w/ lint is coming from Nx falling back on angular CLI's test logic which doesn't know how to read executors, only builders which this extension doesn't currently provide.
> 
> Changing the lint script to `nx run-many --target test --all` would match the behavior you are currently expecting.

`nx run-many --target test --all` worked! Thanks
