### ISSUE TITLE
[BUG] restore and sync fail

### ISSUE THREAD

**Issue by georgechond94** [nx-dotnet/nx-dotnet#465]
**Describe the bug**

@AgentEnder I am getting the following error with both `nx g @nx-dotnet/core:sync` and `nx g @nx-dotnet/core:restore` (which runs as postinstall task during `pnpm install`):

```
>  NX  Generating @nx-dotnet/core:restore

Executing Command: dotnet "restore" "undefined/foo.csproj"
MSBUILD : error MSB1009: Project file does not exist.
Switch: undefined/foo.csproj

 >  NX   dotnet execution returned status code 1
```

After passing `--verbose` I see the following stack trace: 

```
Error: dotnet execution returned status code 1
    at DotNetClient.logAndExecute (D:\source\repos\nx\foo\node_modules\.pnpm\@nx-dotnet+dotnet@1.12.0_kptnhmnqtji5wgbzvc6od2leri\node_modules\@nx-dotnet\dotnet\src\lib\core\dotnet.client.js:159:19)
    at DotNetClient.restorePackages (D:\source\repos\nx\foo\node_modules\.pnpm\@nx-dotnet+dotnet@1.12.0_kptnhmnqtji5wgbzvc6od2leri\node_modules\@nx-dotnet\dotnet\src\lib\core\dotnet.client.js:114:21)
    at D:\source\repos\nx\foo\node_modules\.pnpm\@nx-dotnet+core@1.12.0_qf4sg3l462uolhxnmqtaod4ffa\node_modules\@nx-dotnet\core\src\generators\restore\generator.js:13:30
    at Generator.next (<anonymous>)
    at fulfilled (D:\source\repos\nx\foo\node_modules\.pnpm\tslib@2.4.0\node_modules\tslib\tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Any idea why I am seeing this error?

Note that other generators, like init, application and library work fine

**Comment by AgentEnder** [comment]
Can you share a reproduction for this? It seems like your repo layout may be causing it.

**Comment by georgechond94** [comment]
Hey @AgentEnder thanks for your super fast response!

I think I just found why it's happening. I imported my projects fine by using the `@nx-dotnet/core:import-projects` generator.
This created the following project.json (library example):

```
{
  "$schema": "..\\..\\..\\node_modules\\nx\\schemas\\project-schema.json",
  "targets": {
    "build": {
      "executor": "@nx-dotnet/core:build",
      "outputs": [
        "dist/libs/foo"
      ],
      "options": {
        "configuration": "Debug",
        "noDependencies": true
      },
      "configurations": {
        "production": {
          "configuration": "Release"
        }
      }
    },
    "lint": {
      "executor": "@nx-dotnet/core:format"
    }
  },
  "projectType": "library"
}
```

Adding ` "sourceRoot": "libs/foo",` fixed the issue. (inspired by [link](https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/utils/src/lib/utility-functions/workspace.ts#L123)

Here is the end file
```
{
  "$schema": "..\\..\\..\\node_modules\\nx\\schemas\\project-schema.json",
  "sourceRoot": "libs/foo", <- added
  "targets": {
    "build": {
      "executor": "@nx-dotnet/core:build",
      "outputs": [
        "dist/libs/foo"
      ],
      "options": {
        "configuration": "Debug",
        "noDependencies": true
      },
      "configurations": {
        "production": {
          "configuration": "Release"
        }
      }
    },
    "lint": {
      "executor": "@nx-dotnet/core:format"
    }
  },
  "projectType": "library"
}
```

**Comment by AgentEnder** [comment]
Ah, I should check usage of that since source root is not required. Thanks for the report

**Comment by AgentEnder** [comment]
This was fixed by #543
