### ISSUE TITLE
[BUG] @nx-dotnet/core:test fails to generate test project

### ISSUE THREAD

**Issue by krokofant** [nx-dotnet/nx-dotnet#493]
**Describe the bug**
The generator @nx-dotnet/core:test fails to add a test project

**To Reproduce**

1. `git clone https://github.com/krokofant/nx-dotnet-reproduction.git`
2. `npm ci`
3. `npx nx g @nx-dotnet/core:test --name my-lib --testTemplate xunit --language c# --pathScheme nx`

```powershell
>  NX  Generating @nx-dotnet/core:test

C:\Users\krokofant\repos\nx-dotnet-test-generation-issue\node_modules\enquirer\lib\types\array.js:69
      for (let i = 0; i < items.length; i++) {
                                ^

TypeError: Cannot read properties of undefined (reading 'length')
    at toChoices (C:\Users\krokofant\repos\nx-dotnet-test-generation-issue\node_modules\enquirer\lib\types\array.js:69:33)
    at AutoComplete.toChoices (C:\Users\krokofant\repos\nx-dotnet-test-generation-issue\node_modules\enquirer\lib\types\array.js:80:12)
    at AutoComplete.reset (C:\Users\krokofant\repos\nx-dotnet-test-generation-issue\node_modules\enquirer\lib\types\array.js:34:49)
    at AutoComplete.initialize (C:\Users\krokofant\repos\nx-dotnet-test-generation-issue\node_modules\enquirer\lib\types\array.js:25:16)
    at C:\Users\krokofant\repos\nx-dotnet-test-generation-issue\node_modules\enquirer\lib\prompt.js:236:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Expected behavior**
It should work as described in docs. Should create test project.

**Environment:**

- OS: Windows 11
- nx-dotnet: 1.13.0

**Additional context**

**Comment by AgentEnder** [comment]
Can you run `dotnet new --list` and paste the output here?

**Comment by krokofant** [comment]
@AgentEnder 
```
These templates matched your input: 

Template Name                                 Short Name           Language    Tags                      
--------------------------------------------  -------------------  ----------  --------------------------
ASP.NET Core Empty                            web                  [C#],F#     Web/Empty                 
ASP.NET Core gRPC Service                     grpc                 [C#]        Web/gRPC                  
ASP.NET Core Web API                          webapi               [C#],F#     Web/WebAPI                
ASP.NET Core Web App                          webapp,razor         [C#]        Web/MVC/Razor Pages       
ASP.NET Core Web App (Model-View-Controller)  mvc                  [C#],F#     Web/MVC                   
ASP.NET Core with Angular                     angular              [C#]        Web/MVC/SPA               
ASP.NET Core with React.js                    react                [C#]        Web/MVC/SPA               
Blazor Server App                             blazorserver         [C#]        Web/Blazor                
Blazor WebAssembly App                        blazorwasm           [C#]        Web/Blazor/WebAssembly/PWA
Class Library                                 classlib             [C#],F#,VB  Common/Library            
Console App                                   console              [C#],F#,VB  Common/Console            
dotnet gitignore file                         gitignore                        Config                    
Dotnet local tool manifest file               tool-manifest                    Config                    
EditorConfig file                             editorconfig                     Config                    
global.json file                              globaljson                       Config                    
MSTest Test Project                           mstest               [C#],F#,VB  Test/MSTest               
MVC ViewImports                               viewimports          [C#]        Web/ASP.NET               
MVC ViewStart                                 viewstart            [C#]        Web/ASP.NET               
NuGet Config                                  nugetconfig                      Config                    
NUnit 3 Test Item                             nunit-test           [C#],F#,VB  Test/NUnit                
NUnit 3 Test Project                          nunit                [C#],F#,VB  Test/NUnit                
PowerShell Standard Module                    psmodule             [C#]        Library/PowerShell/Module 
Protocol Buffer File                          proto                            Web/gRPC                  
Razor Class Library                           razorclasslib        [C#]        Web/Razor/Library         
Razor Component                               razorcomponent       [C#]        Web/ASP.NET               
Razor Page                                    page                 [C#]        Web/ASP.NET               
Solution File                                 sln                              Solution                  
Web Config                                    webconfig                        Config                    
Windows Forms App                             winforms             [C#],VB     Common/WinForms           
Windows Forms Class Library                   winformslib          [C#],VB     Common/WinForms           
Windows Forms Control Library                 winformscontrollib   [C#],VB     Common/WinForms           
Worker Service                                worker               [C#],F#     Common/Worker/Web         
WPF Application                               wpf                  [C#],VB     Common/WPF                
WPF Class Library                             wpflib               [C#],VB     Common/WPF                
WPF Custom Control Library                    wpfcustomcontrollib  [C#],VB     Common/WPF                
WPF User Control Library                      wpfusercontrollib    [C#],VB     Common/WPF                
xUnit Test Project                            xunit                [C#],F#,VB  Test/xUnit                

```

**Comment by AgentEnder** [comment]
In `node_modules/@nx-dotnet/core/src/generators/utils/prompt-for-template` can you add `console.log({search, language, available})` under neath the declaration of `available` and try to rerun the command and paste that here too?

**Comment by krokofant** [comment]
@AgentEnder This does nothing for the output of the command in the first post:
`npx nx g @nx-dotnet/core:test --name my-lib --testTemplate xunit --language c# --pathScheme nx`

I tried a throw and error as well, it doesn't seem like it's called at all.

**Comment by AgentEnder** [comment]
Ah! Thats interesting... I thought it was part of our code but it looks like it may be part of the Nx code that throws. Let me investigate.

**Comment by krokofant** [comment]
@AgentEnder Could it have to do anything with nx replacing inquirer with enquirer? I see nx-dotnet has inquirer as a dependency 🤔

https://github.com/nrwl/nx/commit/9cb23ddbbd42975bc7bb992438199564b029dfee

**Comment by AgentEnder** [comment]
Its a bug in Nx, I'll post a PR soon and link it here. To bypass, you can pass `--suffix` on the command line

**Comment by AgentEnder** [comment]
https://github.com/nrwl/nx/pull/11737

**Comment by AgentEnder** [comment]
Should be fixed in next Nx release, keep your eyes out.

**Comment by krokofant** [comment]
@AgentEnder Thanks for the swift fix!
