### ISSUE TITLE
[BUG] webapi project's swagger executor fails with path exception

### ISSUE THREAD

**Issue by Tungsten78** [nx-dotnet/nx-dotnet#594]
**Describe the bug**
"swagger" action for project does not work.  

Suspect this might be windows pathing specific?

**To Reproduce**
`nx swagger [my-web-project]

```
System.ArgumentException: Path "/Users/CML0906/Source/nx-workspaces/repo/dist/apps/builder-api/net7.0/Repo.BuilderApi.dll" is not an absolute path. (Parameter 'assemblyPath')
```

**Expected behavior**
Action succeeds, swagger.json is generated at `libs/generated/[my-web-project]-swagger/swagger.json`

**Screenshots**
```
C:\Users\CML0906\Source\nx-workspaces\repo>nx swagger builder-api

> nx run builder-api:build

Executing Command: dotnet "--version"
7.0.102
Executing Command: dotnet "build" "C:\Users\CML0906\Source\nx-workspaces\repo\apps\builder-api\Repo.BuilderApi.csproj" "--configuration" "Debug" "--no-dependencies" "--verbosity" "minimal"
MSBuild version 17.4.1+9a89d02ff for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Repo.BuilderApi -> C:\Users\CML0906\Source\nx-workspaces\repo\dist\apps\builder-api\net7.0\Repo.BuilderApi.dll
  Checking module boundaries for builder-api
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:02.79

> nx run builder-api:swagger

Executing Command: dotnet "tool" "install" "Swashbuckle.AspNetCore.Cli" "--version" "6.4.0"
You can invoke the tool from this directory using the following commands: 'dotnet tool run swagger' or 'dotnet swagger'.
Tool 'swashbuckle.aspnetcore.cli' (version '6.4.0') was successfully installed. Entry is added to the manifest file C:\Users\CML0906\Source\nx-workspaces\repo\.config\dotnet-tools.json.
Executing Command: dotnet "tool" "run" "swagger" "tofile" "--output" "libs/generated/builder-api-swagger/swagger.json" "/Users/CML0906/Source/nx-workspaces/repo/dist/apps/builder-api/net7.0/Repo.BuilderApi.dll" "v1"
Unhandled exception. System.ArgumentException: Path "/Users/CML0906/Source/nx-workspaces/repo/dist/apps/builder-api/net7.0/Repo.BuilderApi.dll" is not an absolute path. (Parameter 'assemblyPath')
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 82
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 121
 >  NX   dotnet execution returned status code 3762504530
   Pass --verbose to see the stacktrace.

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Ran target swagger for project builder-api and 1 task(s) they depend on (13s)

**Comment by Tungsten78** [comment]
It appears `System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)` expects the drive prefix in windows.

**Comment by AgentEnder** [comment]
Interesting, we probably need to include it whenever we are passing it into the swagger tool. Do you want to submit a PR? The relevant code is in packages/core/src/executors/update-swagger/executor.ts

**Comment by Tungsten78** [comment]
Certainly able/willing to contribute.   I suspect [`path.resolve`](https://nodejs.org/api/path.html#pathresolvepaths) will work here.
