### ISSUE TITLE
[BUG] Error when running `nx build` right after .net project creation

### ISSUE THREAD

**Issue by jimsleon** [nx-dotnet/nx-dotnet#73]
**Describe the bug**
Get follow errors when running `nx build` after creating .net project using nx-dotnet

**To Reproduce**

1. Create a Nx react workspace
2. Generate a webapi .net project using `nx-dotnet`
3. Run `nx build` command

**Expected behavior**
should build successfully

**Screenshots**
```
C:\Repos\test-nx-dotnet>nx build
Looking for project files at 'apps/test-service/**/*.*proj'
Looking for project files at 'apps/test-service-test/**/*.*proj'
nx-dotnet encountered an error parsing dependencies for test-service-test
(node:12964) UnhandledPromiseRejectionWarning: TypeError: builder.getProjectGraph is not a function
    at Object.processProjectGraph (C:\Repos\test-nx-dotnet\node_modules\@nx-dotnet\core\src\graph\process-project-graph.js:19:20)
    at C:\Repos\test-nx-dotnet\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:134:23
    at Array.reduce (<anonymous>)
    at updateProjectGraphWithPlugins (C:\Repos\test-nx-dotnet\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:130:20)
    at buildProjectGraph (C:\Repos\test-nx-dotnet\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:107:15)
    at createProjectGraph (C:\Repos\test-nx-dotnet\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:71:26)
    at Object.<anonymous> (C:\Repos\test-nx-dotnet\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:40:16)
    at Generator.next (<anonymous>)
    at C:\Repos\test-nx-dotnet\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a 
promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Environment:**

- OS: [Windows 10]
- Version [0.15.0]
- Nx [12.6.2]

**Additional Context**
generator config:
```
  "generators": {
    "@nx-dotnet/core:app": {
      "language": "C#",
      "tags": "type:api",
      "template": "webapi",
      "testTemplate": "xunit"
    },
    "@nx-dotnet/core:lib": {
      "language": "C#",
      "template": "classlib",
      "testTemplate": "xunit"
    }
```

**Comment by goldsam** [comment]
I'm experiencing this as well.

**Comment by FairlieAgile** [comment]
I am also experiencing this after migrating @nrwl/angular from 12.4.0 to 12.6.2

**Comment by jimsleon** [comment]
@goldsam @FairlieAgile 
As a temporary solution, you can try to change the `process-project-graph.js` file to make it work with nx 12.6.2. hope it could solve your problem.

- Change line 19 from `return builder.getProjectGraph();` to `return builder.getUpdatedProjectGraph();`
- Change line 24 from `builder.addDependency(DependencyType.Static, projectName, dependencyName);` to 
`builder.addImplicitDependency(projectName, dependencyName);`

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.processProjectGraph = void 0;
const devkit_1 = require("@nrwl/devkit");
const utils_1 = require("@nx-dotnet/utils");
function processProjectGraph(graph, context) {
    const builder = new devkit_1.ProjectGraphBuilder(graph);
    Object.entries(context.workspace.projects).forEach(([name, project]) => {
        var _a;
        try {
            if ((_a = project.tags) === null || _a === void 0 ? void 0 : _a.some((x) => x === 'nx-dotnet')) {
                visitProject(builder, context, project, name);
            }
        }
        catch (_b) {
            console.warn(`nx-dotnet encountered an error parsing dependencies for ${name}`);
        }
    });
    return builder.getUpdatedProjectGraph();
}
exports.processProjectGraph = processProjectGraph;
function visitProject(builder, context, project, projectName) {
    utils_1.getDependantProjectsForNxProject(projectName, context.workspace, (projectConfig, dependencyName) => {
        builder.addImplicitDependency(projectName, dependencyName);
    });
}
```

**Comment by FairlieAgile** [comment]
thanks @jimsleon . I was about to post the same. I can confirm that solves the issue for me.

**Comment by AgentEnder** [comment]
I'll get this fixed asap, been on vacation :smile:
