### ISSUE TITLE
[BUG] Concurrency errors when accessing same files as parallel test

### ISSUE THREAD

**Issue by EelcoLos** [nx-dotnet/nx-dotnet#731]
### Current Behavior

When testing 2 projects targeting the same file, we get a `CS1202` `The process cannot access the file '' because it is being used by another process`. These are caused by 3 items:
1. a `runtimeconfig.json'`
2. a `.deps.json`
3. a `.dll` file

All the .net standard and .net 6 projects have  `RestorePackagesWithLockFile` on them
```xml
 <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
```
this is the dependency graph
![image](https://github.com/nx-dotnet/nx-dotnet/assets/5102501/b8485b6d-9195-406e-a7b6-ea9f924bbf50)

### Expected Behavior

That the `nx affected --target test` runs and does not lock the file, therefore running the `dotnet` projects parallel

### Steps to Reproduce

1. Have 3 dotnet items(projects/libs) with test projects, where 1 project is being used by 2 test projects
2. (don't know if this is affecting it) Have package restore on them
3. run the tests

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.3.0
   OS     : win32 x64
   npm    : 9.6.4
   Hasher : Native

   nx                 : 16.0.3
   @nx/js             : 16.0.3
   @nx/jest           : 16.0.3
   @nx/linter         : 16.0.3
   @nx/workspace      : 16.0.3
   @nx/angular        : 16.0.3
   @nx/cypress        : 16.0.3
   @nx/devkit         : 16.0.3
   @nx/eslint-plugin  : 16.0.3
   @nx/plugin         : 16.0.3
   @nrwl/tao          : 16.0.3
   @nx/webpack        : 16.0.3
   nx-cloud           : 16.0.5
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.12.1
   @ngrx/component-store            : 15.4.0
   @ngrx/component                  : 15.4.0
   @ngrx/effects                    : 15.4.0
   @ngrx/entity                     : 15.4.0
   @ngrx/router-store               : 15.4.0
   @ngrx/store-devtools             : 15.4.0
   @ngrx/store                      : 15.4.0
   @ngrx/schematics                 : 15.4.0
   @nx-dotnet/core                  : 1.22.0
   ---------------------------------------
   Local workspace plugins:
         @meteninbim/workspace-plugin
```

### nx.json

```json
{
	"npmScope": "meteninbim",
	"affected": {
		"defaultBase": "master"
	},
	"tasksRunnerOptions": {
		"default": {
			"runner": "nx-cloud",
			"options": {
				"cacheableOperations": ["build", "lint", "test", "e2e"],
				"parallel": 3
			}
		}
	},
	"plugins": ["@nx-dotnet/core"],
	"generators": {
		"@nx/angular:application": {
			"style": "scss",
			"linter": "eslint",
			"unitTestRunner": "jest",
			"e2eTestRunner": "cypress"
		},
		"@nx/angular:library": {
			"linter": "eslint",
			"unitTestRunner": "jest"
		},
		"@schematics/angular:component": {
			"style": "scss",
			"changeDetection": "OnPush",
			"project": "client",
			"path": "apps/client/src/app"
		},
		"@nx/angular:component": {
			"style": "scss",
			"changeDetection": "OnPush",
			"project": "client",
			"path": "apps/client/src/app"
		}
	},
	"$schema": "./node_modules/nx/schemas/nx-schema.json",
	"cli": {
		"cache": {
			"enabled": true
		}
	},
	"targetDefaults": {
		"build": {
			"dependsOn": ["^build"],
			"inputs": ["production", "^production"]
		},
		"test": {
			"inputs": [
				"default",
				"^production",
				"{workspaceRoot}/jest.preset.js"
			]
		},
		"lint": {
			"inputs": ["default", "{workspaceRoot}/.eslintrc.json"]
		},
		"lint-fix": {
			"inputs": ["default", "{workspaceRoot}/.eslintrc.json"]
		},
		"serve": {
			"dependsOn": ["^build"]
		}
	},
	"namedInputs": {
		"default": ["{projectRoot}/**/*", "sharedGlobals"],
		"sharedGlobals": [],
		"production": [
			"default",
			"!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
			"!{projectRoot}/tsconfig.spec.json",
			"!{projectRoot}/jest.config.[jt]s",
			"!{projectRoot}/.eslintrc.json"
		]
	}
}
```

### Failure Logs

```shell
Executing Command: dotnet "test" "C:\Source\repos\DigitaalMeten\3d\meteninbim\apps\api-integration-test\Meteninbim.Api.IntegrationTest.csproj" "--settings" "../../csharp.runsettings" "--results-directory" "../../coverage/apps/api-integration-test"
  Determining projects to restore...
         Restored C:\Source\repos\DigitaalMeten\3d\meteninbim\apps\api\Meteninbim.Api.csproj (in 724 ms).
         7 of 8 projects are up-to-date for restore.
         Meteninbim.Bimsync -> C:\Source\repos\DigitaalMeten\3d\meteninbim\dist\libs\bimsync\netstandard2.0\Meteninbim.Bimsync.dll
         Meteninbim.Common -> C:\Source\repos\DigitaalMeten\3d\meteninbim\dist\libs\shared\MeteninBim.Common\netstandard2.0\Meteninbim.Common.dll
       CSC : error CS2012: Cannot open 'C:\Source\repos\DigitaalMeten\3d\meteninbim\libs\business\obj\Debug\net6.0\Meteninbim.Business.dll' for writing -- 'The process cannot access the file 'C:\Source\repos\DigitaalMeten\3d\meteninbim\libs\business\obj\Debug\net6.0\Meteninbim.Business.dll' because it is being used by another process.' [C:\Source\repos\DigitaalMeten\3d\meteninbim\libs\business\Meteninbim.Business.csproj]
         Meteninbim.Shared.Startup -> C:\Source\repos\DigitaalMeten\3d\meteninbim\dist\libs\shared\startup\net6.0\Meteninbim.Shared.Startup.dll
       Error: dotnet execution returned status code 1
    at DotNetClient.logAndExecute (C:\Source\repos\DigitaalMeten\3d\meteninbim\node_modules\@nx-dotnet\dotnet\src\lib\core\dotnet.client.js:171:19)
    at DotNetClient.test (C:\Source\repos\DigitaalMeten\3d\meteninbim\node_modules\@nx-dotnet\dotnet\src\lib\core\dotnet.client.js:78:25)
    at C:\Source\repos\DigitaalMeten\3d\meteninbim\node_modules\@nx-dotnet\core\src\executors\test\executor.js:17:41
    at Generator.next (<anonymous>)
    at fulfilled (C:\Source\repos\DigitaalMeten\3d\meteninbim\node_modules\tslib\tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional Information

i tried removing `RestorePackagesWithLockFile`, but this still showed the same error

**Comment by georgechond94** [comment]
Same issue here but when `nx affected --target publish`ing

**Comment by Flusinerd** [comment]
I think I'm encountering a similar issue when running ``nx affected:test`` with a .NET project that has a testing project attached:
```
Executing Command: dotnet "test" "/root/project/apps/navigatem-pze-api-test/Datenlotse.NavigatemPzeApi.Test.csproj"
  Determining projects to restore...
  All projects are up-to-date for restore.
/root/project/apps/navigatem-pze-api/Services/Urlaubsanspruch/UrlaubsantragService.cs(105,52): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018: The "GenerateRuntimeConfigurationFiles" task failed unexpectedly. [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018: System.IO.IOException: The process cannot access the file '/root/project/dist/apps/navigatem-pze-api/net7.0/Datenlotse.NavigatemPzeApi.runtimeconfig.json' because it is being used by another process. [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions) [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException) [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018:    at System.IO.File.Create(String path) [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteToJsonFile(String fileName, Object value) [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteRuntimeConfig(RuntimeFramework[] runtimeFrameworks, LockFileTargetLibrary platformLibrary, Boolean isFrameworkDependent, IList`1 packageFolders) [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.ExecuteCore() [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
/usr/share/dotnet/sdk/7.0.305/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(292,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/root/project/apps/navigatem-pze-api/Datenlotse.NavigatemPzeApi.csproj]
Error: dotnet execution returned status code 1
    at DotNetClient.logAndExecute (/root/project/node_modules/@nx-dotnet/dotnet/src/lib/core/dotnet.client.js:171:19)
    at DotNetClient.test (/root/project/node_modules/@nx-dotnet/dotnet/src/lib/core/dotnet.client.js:78:25)
    at /root/project/node_modules/@nx-dotnet/core/src/executors/test/executor.js:17:41
    at Generator.next (<anonymous>)
    at fulfilled (/root/project/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

**Comment by mxa0079** [comment]
Any updates? Our CI is being very flaky do to this issue.

**Comment by EelcoLos** [comment]
> Any updates? Our CI is being very flaky do to this issue.

as a workaround, you can set parallel to `false`. It at least stabilizes your CI, so you can deploy steadily

**Comment by limeship-chd** [comment]
Also experiencing this issue very frequently (`CS2012` and `GenerateDepsFile` failures) probably due to parallelism. Might be an issue with the dotnet sdk since there are quite a few issues on their repo as well, e.g. https://github.com/dotnet/sdk/issues/2902

I tried disabling parallelism via a dotnet param
```json
"options": {
    "extraParameters": "/maxcpucount:1"
}
```
and by limiting nx parallelism
```json
"tasksRunnerOptions": {
        "default": {
            "runner": "nx/tasks-runners/default",
            "options": {
                "cacheableOperations": ["build", "lint", "test", "e2e"],
                "parallel": 1
            }
        }
    }
```
but so far this also didn't help. In my case it looks like a shared library is being built twice, where the first build is failing due to concurrency issues but the second build works.

**Comment by limeship-chd** [comment]
@georgechond94 What version of nx are you using? We are on v16 and according to the current schema, boolean isn't an option for that anymore: https://github.com/nrwl/nx/blob/master/packages/nx/schemas/nx-schema.json#L230

But either way to give an update, it seems like for us this happened when two different shells tried to run build commands in parallel, this was a part in our code though. For now, limiting `parallel ` and/or setting `/maxcpucount:1` should be enough.

**Comment by EchelonFour** [comment]
I think i have fixed this issue by putting this in the nx.json:
```json
{
  "targetDefaults": {
    "@nx-dotnet/core:test": {
      "dependsOn": ["build"],
      "options": {
        "noBuild": true
      }
    }
  }
}
```
This works for the same reasons as layed out in https://www.nx-dotnet.com/docs/core/guides/incremental-builds.
This makes sure the build is done before running tests and importantly all dependant builds are done also. Then when two tests run at the same time with the same dependency, they don't rebuild the dependency at the same time and hit this error.

Should also make testing faster because it can use nx's build cache.

I'm not certain this has fixed it, because the issue is intermittent and maybe I am just lucky.

**Comment by vzakanj** [comment]
> 

We are currently on 16.2.1 and setting the parallel to false works fine, e.g.

```bash
nx run-many --parallel=false --targets=release --projects=tag:scope:service,tag:scope:web,tag:scope:migration
```

Alternatively, I think you could solve the parallel builds through msbuild, but that would probably invalidate the whole point of using the nx cache.

**Comment by AgentEnder** [comment]
How would you do it differently with msbuild? My understanding is dotnet
build should be equivalent and that's all the plugin does under the hood

**Comment by vzakanj** [comment]
@AgentEnder it is equivalent, but if you really want to, what you could do is create an msbuild file which builds multiple projects in parallel and then do a single dotnet build/release command.

But that's why I said that would invalidate the whole point of using the nx cache since it would end up as a single nx target.

What I'm personally doing now is using parallel=false for local builds and am in the process of moving to containerized builds in CI.

**Comment by corwestermaniddink** [comment]
> I think i have fixed this issue by putting this in the nx.json:
> 
> ```json
> {
>   "targetDefaults": {
>     "@nx-dotnet/core:test": {
>       "dependsOn": ["build"],
>       "options": {
>         "noBuild": true
>       }
>     }
>   }
> }
> ```
> 
> This works for the same reasons as layed out in https://www.nx-dotnet.com/docs/core/guides/incremental-builds. This makes sure the build is done before running tests and importantly all dependant builds are done also. Then when two tests run at the same time with the same dependency, they don't rebuild the dependency at the same time and hit this error.
> 
> Should also make testing faster because it can use nx's build cache.
> 
> I'm not certain this has fixed it, because the issue is intermittent and maybe I am just lucky.

I can confirm this, but don't forget to do a nx -t build of the test project(s) first and then nx -t test:

**Comment by AgentEnder** [comment]
A depends on config would handle this :thinking_face:

**Comment by EchelonFour** [comment]
> https://github.com/nx-dotnet/nx-dotnet/issues/731#issuecomment-1700295028
> I'm not certain this has fixed it, because the issue is intermittent and maybe I am just lucky.

Months later I have not seen this issue reappear. I no longer think I might be lucky, I think I have solved it.

**Comment by AgentEnder** [comment]
Yes, this is likely the correct solution. I'll likely work on an update to nx-dotnet to better support this in the near future.

**Comment by wojtek-viirtue** [comment]
Just wanted to follow up here too.  We're seeing the same locally when running builds with parallelization.  It takes 1-2 tries to get past the errors and get everything to go green. As previously mentioned by others, we need to disable parallelization in CI in order to avoid the aforementioned, but it makes things pretty slow.  Here's some log output confirm what others have also describe:

```
dotnet-billing:        (GenerateBuildDependencyFile target) -> 
dotnet-billing:          /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018: System.IO.IOException: The process cannot access the file '/Users/wojtek/src/Acme/redacted/dist/libs/dotnet/shared/util/Acme.Util/net6.0/Acme.Util.deps.json' because it is being used by another process. [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at System.IO.File.Create(String path) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
dotnet-billing:     14 Warning(s)
dotnet-billing:     1 Error(s)
dotnet-billing: Time Elapsed 00:00:31.50
dotnet-billing:  >  NX   dotnet execution returned status code 1
dotnet-billing:    Pass --verbose to see the stacktrace.
```

**Comment by AgentEnder** [comment]
> Just wanted to follow up here too.  We're seeing the same locally when running builds with parallelization.  It takes 1-2 tries to get past the errors and get everything to go green. As previously mentioned by others, we need to disable parallelization in CI in order to avoid the aforementioned, but it makes things pretty slow.  Here's some log output confirm what others have also describe:
> 
> ```
> dotnet-billing:        (GenerateBuildDependencyFile target) -> 
> dotnet-billing:          /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
> dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018: System.IO.IOException: The process cannot access the file '/Users/wojtek/src/Acme/redacted/dist/libs/dotnet/shared/util/Acme.Util/net6.0/Acme.Util.deps.json' because it is being used by another process. [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
> dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
> dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
> dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
> dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at System.IO.File.Create(String path) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
> dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
> dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
> dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
> dotnet-billing:        /usr/local/share/dotnet/sdk/7.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/wojtek/src/Acme/redacted/libs/dotnet/shared/util/Acme.Util/Acme.Util.csproj]
> dotnet-billing:     14 Warning(s)
> dotnet-billing:     1 Error(s)
> dotnet-billing: Time Elapsed 00:00:31.50
> dotnet-billing:  >  NX   dotnet execution returned status code 1
> dotnet-billing:    Pass --verbose to see the stacktrace.
> ```
> 

Set noBuild true for the test target, no dependencies true for the build target, and test to depend on build, and build to depend on dependant project builds

**Comment by mxa0079** [comment]
@AgentEnder - could you please give an example on the following recommended configuration (and some explanation would be great as well, specially with the no dependencies true for the build target... since in my case the build target does have dependencies setting it to false makes me scratch my head) : _"Set noBuild true for the test target, no dependencies true for the build target, and test to depend on build, and build to depend on dependant project builds"_

**Comment by AgentEnder** [comment]
No dependencies tells the dotnet CLI not to build dependencies automatically. This is what we want, since we are setting Nx up to build the dependencies first on its side. Otherwise we would be building dependencies twice
