### ISSUE TITLE
[BUG] Locked files during npm ci

### ISSUE THREAD

**Issue by enorfelt** [nx-dotnet/nx-dotnet#856]
### Current Behavior

Our devops pipeline fails on `npm ci` step

### Expected Behavior

That `npm ci` step succeeds

### Steps to Reproduce

1. Setup a new nx repo with @nx-dotnet as dependency
2. Create a devops pipeline with a task for  `npm ci`
3. Trigger the pipeline

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : win32-x64
npm    : 10.2.3

nx             : 19.0.4
@nx/js         : 19.0.4
@nx/jest       : 19.0.4
@nx/linter     : 19.0.4
@nx/eslint     : 19.0.4
@nx/workspace  : 19.0.4
@nx/angular    : 19.0.4
@nx/devkit     : 19.0.4
@nrwl/tao      : 19.0.4
@nx/web        : 19.0.4
@nx/webpack    : 19.0.4
typescript     : 5.3.3
---------------------------------------
Registered Plugins:
@nx/jest/plugin
@nx-dotnet/core
---------------------------------------
Community plugins:
@ngrx/effects            : 17.1.1
@ngrx/eslint-plugin      : 17.1.0
@ngrx/router-store       : 17.1.1
@ngrx/store              : 17.1.1
@ngrx/store-devtools     : 17.1.1
@nx-dotnet/core          : 2.2.0
@storybook/angular       : 7.6.17
@testing-library/angular : 15.2.0
devextreme-angular       : 23.1.8
ng-mocks                 : 14.12.1
ngrx-immer               : 2.1.1
```

### nx.json

```json
{
  "namedInputs": {
    "sharedGlobals": [],
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/src/test-setup.[jt]s",
      "!{projectRoot}/test-setup.[jt]s"
    ]
  },
  "targetDefaults": {
    "build": {
      "dependsOn": [
        "^build"
      ],
      "inputs": [
        "production",
        "^production"
      ],
      "cache": true
    },
    "@nx/jest:jest": {
      "cache": true,
      "inputs": [
        "default",
        "^production",
        "{workspaceRoot}/jest.preset.js"
      ],
      "options": {
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    }
  },
  "plugins": [
    {
      "plugin": "@nx/jest/plugin",
      "exclude": [
        "e2e/**/*"
      ],
      "options": {
        "targetName": "test"
      }
    },
    {
      "plugin": "@nx-dotnet/core",
      "options": {
        "solutionFile": "{npmScope}.nx-dotnet.sln",
        "inferProjects": true,
        "nugetPackages": {
          "Microsoft.AspNetCore.SpaServices.Extensions": "8",
          "Yarp.ReverseProxy": "2.1.0"
        },
        "inferredTargets": {
          "build": "build",
          "lint": "lint",
          "serve": "serve",
          "test": "test"
        },
        "ignorePaths": [],
        "tags": [
          "nx-dotnet"
        ]
      }
    }
  ],
  "useInferencePlugins": false,
  "defaultBase": "origin/master"
}
```

### Failure Logs

```shell
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\src\\_work\\2\\s\\node_modules\\nx',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\src\_work\2\s\node_modules\nx'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\src\\_work\\2\\s\\node_modules\\nx'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\src\\_work\\2\\s\\node_modules\\ng-packagr\\node_modules\\esbuild',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\src\_work\2\s\node_modules\ng-packagr\node_modules\esbuild'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\src\\_work\\2\\s\\node_modules\\ng-packagr\\node_modules\\esbuild'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\src\\_work\\2\\s\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\src\_work\2\s\node_modules\nx'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\src\\_work\\2\\s\\node_modules\\nx'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\src\_work\2\s\node_modules\@nx-dotnet\utils\node_modules\nx
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./bin/post-install
npm ERR! C:\src\_work\2\s\node_modules\@nx-dotnet\utils\node_modules\nx\src\native\native-bindings.js:244
npm ERR!     throw loadError
npm ERR!     ^
npm ERR! 
npm ERR! Error: The process cannot access the file because it is being used by another process.
npm ERR! \\?\C:\src\_work\2\s\.nx\cache\18.3.4-nx.win32-x64-msvc.node
npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
npm ERR!     at Module._load (C:\src\_work\2\s\node_modules\@nx-dotnet\utils\node_modules\nx\src\native\index.js:58:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR!     at Object.<anonymous> (C:\src\_work\2\s\node_modules\@nx-dotnet\utils\node_modules\nx\src\native\native-bindings.js:66:29)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32) {
npm ERR!   code: 'ERR_DLOPEN_FAILED'
npm ERR! }
npm ERR! 
npm ERR! Node.js v20.10.0
```

### Additional Information

I think that nx has a fix for this in latest version. https://github.com/nrwl/nx/pull/23375
I would appreciate if you could update nx to this version.

**Comment by enorfelt** [comment]
I can see that you have started upgrade to nx 19 @AgentEnder . Thx! Cant wait :) Hopefully it will resolve this issue. I think it relates to this change: https://github.com/nrwl/nx/pull/23375

**Comment by AgentEnder** [comment]
I think this should be fixed now that the Nx 19 work is pushed
