### ISSUE TITLE
[BUG] nx affected random failures (System.IO.IOException)

### ISSUE THREAD

**Issue by mrfelton** [nx-dotnet/nx-dotnet#901]
### Current Behavior

`nx affected` randomly fails

### Expected Behavior

`nx affected` should work everytime without fail

### Steps to Reproduce

Impossible to reproduce, it happens randomly

### Nx Report

```shell
❯ nx report

 NX   Report complete - copy this into the issue template

Node           : 20.11.1
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 8.15.5

nx               : 19.7.0
@nx/js           : 19.7.0
@nrwl/js         : 18.0.8
@nx/jest         : 18.0.8
@nx/linter       : 18.0.8
@nx/eslint       : 19.7.0
@nx/workspace    : 19.7.0
@nrwl/workspace  : 18.0.8
@nx/devkit       : 19.7.0
@nrwl/devkit     : 18.0.8
@nx/plugin       : 19.7.0
@nrwl/nx-plugin  : 18.0.8
@nrwl/tao        : 18.0.8
typescript       : 5.5.4
---------------------------------------
Registered Plugins:
@nx-dotnet/core
---------------------------------------
Community plugins:
@nx-dotnet/core        : 2.4.5
@nx-tools/nx-container : 6.0.2
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/js@18.0.8
  - @nx/jest@18.0.8
  - @nrwl/jest@18.0.8
  - @nx/linter@18.0.8
  - @nrwl/workspace@18.0.8
  - @nrwl/devkit@18.0.8
  - @nrwl/nx-plugin@18.0.8
  - @nrwl/tao@18.0.8

To fix this, run `nx migrate nx@19.7.0
```

### nx.json

```json
n/a
```

### Failure Logs

```shell
> pnpm nx show projects --affected --projects=tag:nx-dotnet --sep=, --verbose

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  The "@nx-dotnet/core" plugin threw an error while creating dependencies:
    Error: dotnet execution returned status code 1 
     Command failed: dotnet list src/PlaidAdapter/ZapMiddleware.PlaidAdapter.Contracts/ZapMiddleware.PlaidAdapter.Contracts.csproj reference
    System.IO.IOException: The system cannot open the device or file specified. : '\''NuGet-Migrations'\''
       at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
       at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
       at NuGet.Common.Migrations.MigrationRunner.Run(String migrationsDirectory)
       at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
       at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
       at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
       at Microsoft.DotNet.Cli.Program.Main(String[] args)
    
        at /home/runner/_work/zap-middleware/zap-middleware/node_modules/.pnpm/@nx-dotnet+dotnet@2.4.5_nx@19.7.0/node_modules/@nx-dotnet/dotnet/src/lib/core/dotnet.client.js:262:23
        at async DotNetClient.spawnAsyncAndGetOutput (/home/runner/_work/zap-middleware/zap-middleware/node_modules/.pnpm/@nx-dotnet+dotnet@2.4.5_nx@19.7.0/node_modules/@nx-dotnet/dotnet/src/lib/core/dotnet.client.js:258:28)
        at async DotNetClient.getProjectReferencesAsync (/home/runner/_work/zap-middleware/zap-middleware/node_modules/.pnpm/@nx-dotnet+dotnet@2.4.5_nx@19.7.0/node_modules/@nx-dotnet/dotnet/src/lib/core/dotnet.client.js:214:24)
        at async getProjectReferences (/home/runner/_work/zap-middleware/zap-middleware/node_modules/.pnpm/@nx-dotnet+core@2.4.5_@nx+js@19.7.0_eslint@8.57.0_nx@19.7.0_prettier@3.2.5/node_modules/@nx-dotnet/core/src/graph/create-dependencies.js:21:36)
        at async Promise.all (index 35)
        at async Promise.all (index 1)
        at async createDependencies (/home/runner/_work/zap-middleware/zap-middleware/node_modules/.pnpm/nx@19.7.0_@swc-node+register@1.9.2_@swc+core@1.5.7/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:88:36)
        at async consumeMessage (/home/runner/_work/zap-middleware/zap-middleware/node_modules/.pnpm/nx@19.7.0_@swc-node+register@1.9.2_@swc+core@1.5.7/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:38:26)'
```

### Additional Information

That happens randomly when running in a CI environment into which dotnet has been freshly installed using setup/dotent action.

**Comment by mrfelton** [comment]
It seems that https://github.com/dotnet/runtime/issues/79375 of the issue is buried deep in the .net runtime and [triggered by NuGet](https://github.com/NuGet/NuGet.Client/blob/2982dbfc1bac22d71234d8498af6ad43e129a49c/src/NuGet.Core/NuGet.Common/Migrations/MigrationRunner.cs#L31-L60) when it tries to perform project migration. We were able to work around this  by adding a step right after using `setup/dotnet` that will that will create NuGet's internal files and make it believe all necessary migrations are already performed, so it won't trigger bug in .net runtime.

```
#!/usr/bin/env bash

XDG_DATA_HOME="${XDG_DATA_HOME:-}"
USER_PROFILE="$HOME"

# Set the migrations directory
if [ -z "$XDG_DATA_HOME" ]; then
    migrationsDirectory="$USER_PROFILE/.local/share/NuGet/Migrations"
else
    migrationsDirectory="$XDG_DATA_HOME/NuGet/Migrations"
fi

# Create the migration directory and files if they don't exist
mkdir -p "$migrationsDirectory"
touch "$migrationsDirectory/1"
```

**Comment by AgentEnder** [comment]
Hello, going through the issues here in order to prepare for the transition to the main nx repo as part of @nx/dotnet.

The new mechanisms do not cause a nuget invocation during graph construction so this should be resolved there.
