### ISSUE TITLE
[BUG] Generating swagger.json throws IOException

### ISSUE THREAD

**Issue by DominikPieper** [nx-dotnet/nx-dotnet#906]
### Current Behavior

Generating the swagger.json throws an error. It's just a regular Nx repo, directories aren't protected or something.

I'm not sure yet but could be my dotnet setup as well. Dotnet sdk is a fresh install, I never used it until now ^^' Other commands like `build` run without a problem

### Expected Behavior

Command should generate the swagger.json

### Github Repo

https://github.com/conciso/angular-dotnet-demo

### Steps to Reproduce

1. run 'npx nx swagger backend'

### Nx Report

```shell
Node           : 18.19.1
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.2.4

nx                 : 19.8.0
@nx/js             : 19.8.0
@nx/jest           : 19.8.0
@nx/linter         : 19.8.0
@nx/eslint         : 19.8.0
@nx/workspace      : 19.8.0
@nx/angular        : 19.8.0
@nx/devkit         : 19.8.0
@nx/eslint-plugin  : 19.8.0
@nrwl/tao          : 19.8.0
@nx/web            : 19.8.0
@nx/webpack        : 19.8.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx-dotnet/core
---------------------------------------
Community plugins:
@nx-dotnet/core : 2.4.5
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/eslint.config.js",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/src/test-setup.[jt]s",
      "!{projectRoot}/test-setup.[jt]s"
    ],
    "sharedGlobals": ["{workspaceRoot}/.github/workflows/ci.yml"]
  },
  "nxCloudId": "66f11bf2927c3b4c91f50da9",
  "targetDefaults": {
    "@angular-devkit/build-angular:application": {
      "cache": true,
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"]
    },
    "@nx/eslint:lint": {
      "cache": true,
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/.eslintignore",
        "{workspaceRoot}/eslint.config.js"
      ]
    },
    "@nx/jest:jest": {
      "cache": true,
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"],
      "options": {
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    },
    "@nx/js:tsc": {
      "cache": true,
      "dependsOn": [
        "^build"
      ],
      "inputs": [
        "production",
        "^production"
      ]
    },
    "build": {
      "dependsOn": [
        "^build",
        "codegen",
        "^codegen"
      ]
    },
    "codegen": {
      "cache": true
    },
    "swagger": {
      "cache": true
    }
  },
  "generators": {
    "@nx/angular:application": {
      "e2eTestRunner": "none",
      "linter": "eslint",
      "style": "css",
      "unitTestRunner": "jest"
    }
  },
  "plugins": [
    "@nx-dotnet/core"
  ]
}
```

### Failure Logs

```shell
npx nx swagger backend

> nx run backend:build  [existing outputs match the cache, left as is]

Executing Command: dotnet "--version"
8.0.401
Executing Command: dotnet "build" "/Users/dominikpieper/Projects/angular-dotnet-demo/apps/backend/AngularDotnetDemo.Backend.csproj" "--configuration=Debug" "--no-dependencies" "--verbosity=minimal"
  Wiederherzustellende Projekte werden ermittelt...
  Alle Projekte sind für die Wiederherstellung auf dem neuesten Stand.
  AngularDotnetDemo.Backend -> /Users/dominikpieper/Projects/angular-dotnet-demo/dist/apps/backend/net8.0/AngularDotnetDemo.Backend.dll
  Checking module boundaries for backend

Der Buildvorgang wurde erfolgreich ausgeführt.
    0 Warnung(en)
    0 Fehler

Verstrichene Zeit 00:00:07.86

> nx run backend:swagger

Executing Command: dotnet "tool" "run" "swagger" "tofile" "--output" "/Users/dominikpieper/Projects/angular-dotnet-demo/generated/backend-swagger" "/Users/dominikpieper/Projects/angular-dotnet-demo/dist/apps/backend/net8.0/AngularDotnetDemo.Backend.dll" "v1"
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/Users/dominikpieper/Projects/angular-dotnet-demo/generated/backend-swagger' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Create(String path)
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs) in /_/src/Swashbuckle.AspNetCore.Cli/Program.cs:line 117
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in /_/src/Swashbuckle.AspNetCore.Cli/CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in /_/src/Swashbuckle.AspNetCore.Cli/CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in /_/src/Swashbuckle.AspNetCore.Cli/Program.cs:line 159

 NX   dotnet execution returned status code 134

Pass --verbose to see the stacktrace.


—————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target swagger for project backend and 1 task(s) they depend on (3s)

   ✖  1/2 failed
   ✔  1/2 succeeded [1 read from cache]

View structured, searchable error logs at https://nx.app/runs/p9Dm3Y1cZJ
```

### Additional Information

Same error on the windows system of my colleague.

dotnet --version
8.0.401

**Comment by DominikPieper** [comment]
Ok I found the problem. Per default the output is set to a folder. The Path need to end with a filename. Maybe some default in the dotnet tool cli changed? With that it works :-)
