### ISSUE TITLE
[BUG] [2.4.5] @nx-dotnet/core timed out after 10 minutes during createDependencies

### ISSUE THREAD

**Issue by roldengarm** [nx-dotnet/nx-dotnet#910]
### Current Behavior

`npx nx migrate --run-migrations` times out after 10 minutes

### Expected Behavior

It does not time out

### Steps to Reproduce

Every month or so I upgrade all nx packages using:
```
npx nx migrate latest
npx nx migrate --run-migrations
```
The second command upgraded from Angular 18.1.5 to 18.2.7 but times out after 10 minutes, with an error related to nx-dotnet, see below.

`npm install` works fine.

### Nx Report

```shell
nx report

 NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.1

nx (global)        : 19.8.3
nx                 : 19.8.3
@nx/js             : 19.8.3
@nx/jest           : 19.8.3
@nx/linter         : 19.8.3
@nx/eslint         : 19.8.3
@nx/workspace      : 19.8.3
@nx/angular        : 19.8.3
@nx/cypress        : 19.8.3
@nx/devkit         : 19.5.3
@nx/eslint-plugin  : 19.8.3
@nrwl/tao          : 19.8.3
@nx/web            : 19.8.3
@nx/webpack        : 19.8.3
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx-dotnet/core
@nx/cypress/plugin
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome : 0.15.0
@jsverse/transloco               : 7.5.0
@nx-dotnet/core                  : 2.4.5
ng2-charts                       : 6.0.1
---------------------------------------
The following packages should match the installed version of nx
  - @nx/devkit@19.5.3
  - @nrwl/devkit@19.5.3

To fix this, run `nx migrate nx@19.8.3`
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "neverConnectToCloud": true,
  "plugins": [
    "@nx-dotnet/core",
    {
      "plugin": "@nx/cypress/plugin",
      "options": {
        "targetName": "e2e",
        "ciTargetName": "e2e-ci",
        "openTargetName": "open-cypress",
        "componentTestingTargetName": "component-test"
      },
      "include": [
      ]
    }
  ],
  "npmScope": "gentext",
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/src/test-setup.[jt]s",
      "!{projectRoot}/cypress/**/*",
      "!{projectRoot}/**/*.cy.[jt]s?(x)",
      "!{projectRoot}/cypress.config.[jt]s",
      "!{projectRoot}/test-setup.[jt]s"
    ],
    "sharedGlobals": [
      "{workspaceRoot}/.github/workflows/*.yml",
      "{workspaceRoot}/infrastructure/**/*",
      "{workspaceRoot}/nx.json"
    ],
    "environment": [
    ]
  },
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build", "codegen", "^codegen", "codegen", "^codegen"],
      "inputs": ["production", "^production", "environment"]
    },
    "test": {
      "inputs": [
        "default",
        "^production",
        "{workspaceRoot}/jest.preset.js",
        "environment"
      ]
    },
    "e2e": {
      "inputs": ["default", "^production", "environment"],
      "cache": true
    },
    "lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/.eslintrc.base.json",
        "environment"
      ]
    },
    "@nx/eslint:lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/.eslintrc.base.json",
        "environment"
      ],
      "cache": true
    }
  },
  "workspaceLayout": {
    "appsDir": "src",
    "libsDir": "src/libs"
  },
  "generators": {
    "@nx/angular:application": {
      "style": "css",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "none"
    },
    "@nx/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
    "@nx/angular:component": {
      "style": "css"
    }
  },
  "defaultProject": "addin"
}
```

### Failure Logs

```shell
npx nx migrate --run-migrations --verbose

 NX   Running 'npm install' to make sure necessary packages are installed


> project@0.0.0 prepare
> nx g @nx-dotnet/core:restore


 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx-dotnet/core plugin.
    - Plugin worker @nx-dotnet/core exited unexpectedly with code 0
      Error: Plugin worker @nx-dotnet/core exited unexpectedly with code 0
          at ChildProcess.<anonymous> (D:\projects\gentext3\node_modules\nx\src\project-graph\plugins\isolation\plugin-pool.js:194:37)
          at ChildProcess.emit (node:events:519:28)
          at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    The "@nx-dotnet/core" plugin threw an error while creating dependencies: @nx-dotnet/core timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
    Error: @nx-dotnet/core timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
        at Timeout.<anonymous> (D:\projects\gentext3\node_modules\nx\src\project-graph\plugins\isolation\plugin-pool.js:219:21)
        at listOnTimeout (node:internal/timers:581:17)
        at process.processTimers (node:internal/timers:519:7)
  Caused by:
      Error: @nx-dotnet/core timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
        at Timeout.<anonymous> (D:\projects\gentext3\node_modules\nx\src\project-graph\plugins\isolation\plugin-pool.js:219:21)
        at listOnTimeout (node:internal/timers:581:17)
        at process.processTimers (node:internal/timers:519:7)
```

### Additional Information

Seems similar to [this issue](https://github.com/nx-dotnet/nx-dotnet/issues/876).

When I run it with `NX_PLUGIN_NO_TIMEOUTS=true` it seems to work fine.

**Comment by Tungsten78** [comment]
Going through nx migrations myself, and seeing a similar hang/error with `nx g @nx-dotnet/core:restore`.

Context:
* migrated from nx 18 -> 19
* migrated to nx-dotnet/core@2.3.2 (last in major line that listed nx 18 support)

in #876, it mentions 2.3.0 was working.   this DOES resolve the issue.
* Tried 2.4.1 as indicated in the resolution notes, this DID NOT resolve the issue.

**Comment by enorfelt** [comment]
@Tungsten78 no new findings on this? Have have the same problem.

**Comment by Tungsten78** [comment]
> @Tungsten78 no new findings on this? Have have the same problem.

No, I’m using 2.3.0 with Nx 20 for now.

**Comment by slenderfigure** [comment]
How come there's still no updates on this after almost 5 months? Do we really need to downgrade to v2.3.0 to somehow get this around?

**Comment by bcallaghan-et** [comment]
Possibly the same issue as #924 ?

**Comment by roldengarm** [comment]
> Hello, going through the issues here in order to prepare for the transition to the main nx repo as part of @nx/dotnet.

That is awesome @AgentEnder ! Any idea about ETA or where I can check progress?
